/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginscreen.Telas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import loginscreen.Classes.*;

/**
 *
 * @author Andre
 */
public class Menu extends javax.swing.JFrame {

    int xMouse;
    int yMouse;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btReturn = new javax.swing.JLabel();
        btSobre = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        btRegras = new javax.swing.JLabel();
        btRanking = new javax.swing.JLabel();
        btDesafio = new javax.swing.JLabel();
        Move = new javax.swing.JLabel();
        btJogar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IGNORAR = new javax.swing.JTextField();
        Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btReturnIn.png"))); // NOI18N
        btReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btReturnMouseExited(evt);
            }
        });
        getContentPane().add(btReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));

        btSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btSobreIn.png"))); // NOI18N
        btSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSobreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSobreMouseExited(evt);
            }
        });
        getContentPane().add(btSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 50, 30));

        btRegras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btRegrasIn.png"))); // NOI18N
        btRegras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRegrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRegrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRegrasMouseExited(evt);
            }
        });
        getContentPane().add(btRegras, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, -1, -1));

        btRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btRankingIn.png"))); // NOI18N
        btRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRankingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRankingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRankingMouseExited(evt);
            }
        });
        getContentPane().add(btRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        btDesafio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btDesafioIn.png"))); // NOI18N
        btDesafio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDesafioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDesafioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDesafioMouseExited(evt);
            }
        });
        getContentPane().add(btDesafio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        Move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoveMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MoveMouseMoved(evt);
            }
        });
        getContentPane().add(Move, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 30));

        btJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btJogarIn.png"))); // NOI18N
        btJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btJogarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btJogarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btJogarMouseExited(evt);
            }
        });
        getContentPane().add(btJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 84, 140, 20));

        IGNORAR.setBackground(new java.awt.Color(153, 153, 153));
        IGNORAR.setEnabled(false);
        getContentPane().add(IGNORAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 30, 20));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/menu.png"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btJogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJogarMouseEntered

        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btJogarOut.png/"));
        btJogar.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btJogarMouseEntered

    private void btJogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJogarMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btJogarIn.png/"));
        btJogar.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btJogarMouseExited

    private void btDesafioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesafioMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btDesafioOut.png/"));
        btDesafio.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btDesafioMouseEntered

    private void btDesafioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesafioMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btDesafioIn.png/"));
        btDesafio.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btDesafioMouseExited

    private void btRankingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRankingMouseEntered

        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btRankingOut.png/"));
        btRanking.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btRankingMouseEntered

    private void btRankingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRankingMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btRankingIn.png/"));
        btRanking.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btRankingMouseExited

    private void btRegrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegrasMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btRegrasOut.png/"));
        btRegras.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btRegrasMouseEntered

    private void btRegrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegrasMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btRegrasIn.png/"));
        btRegras.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btRegrasMouseExited

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked

        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null,
                "Você deseja sair do jogo?", "ATENÇÃO",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[0]);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btSairMouseClicked

    private void btReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseClicked

        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null,
                "Você deseja voltar a tela de login?", "ATENÇÃO",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[0]);
        if (i == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);

            this.dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btReturnMouseClicked

    private void btReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btReturnOut.png/"));
        btReturn.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btReturnMouseEntered

    private void btReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btReturnIn.png/"));
        btReturn.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btReturnMouseExited

    private void btSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSobreMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btSobreOut.png/"));
        btSobre.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btSobreMouseEntered

    private void btSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSobreMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btSobreIn.png/"));
        btSobre.setIcon(ico);

// TODO add your handling code here:
    }//GEN-LAST:event_btSobreMouseExited

    private void MoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);

        // TODO add your handling code here:
    }//GEN-LAST:event_MoveMouseDragged

    private void MoveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveMouseMoved

        xMouse = evt.getX();
        yMouse = evt.getY();

        // TODO add your handling code here:
    }//GEN-LAST:event_MoveMouseMoved

    private void btSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSobreMouseClicked
        QuemSomos QS = new QuemSomos();

        QS.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_btSobreMouseClicked

    private void btRegrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegrasMouseClicked
        Regras regras = new Regras();
        regras.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btRegrasMouseClicked

    private void btRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRankingMouseClicked
        Ranking ranking = new Ranking();

        ranking.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_btRankingMouseClicked

    private void btDesafioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDesafioMouseClicked
        Desafio desafio = new Desafio();

        desafio.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_btDesafioMouseClicked
    public static String id;
    public String nome;
    public int pontos;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            String resp = obj_usuario.get_nome(id);
            jLabel1.setText(resp);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btJogarMouseClicked
        pegarDesafio obj_pegardesafio = new pegarDesafio();
        obj_pegardesafio.set_visible();
        setVisible(false);
    }//GEN-LAST:event_btJogarMouseClicked
    usuario obj_usuario = new usuario();

    public void get_dados(String nome, String senha) throws ClassNotFoundException {

        id = obj_usuario.Get_id(nome, senha);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IGNORAR;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Move;
    private javax.swing.JLabel btDesafio;
    private javax.swing.JLabel btJogar;
    private javax.swing.JLabel btRanking;
    private javax.swing.JLabel btRegras;
    private javax.swing.JLabel btReturn;
    private javax.swing.JLabel btSair;
    private javax.swing.JLabel btSobre;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
