/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginscreen.Telas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Andre
 */
public class QuemSomos extends javax.swing.JFrame {

    int yMouse;
    int xMouse;

    /**
     * Creates new form QuemSomos
     */
    public QuemSomos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IGNORAR = new javax.swing.JTextField();
        fbAndre = new javax.swing.JLabel();
        wppAndre = new javax.swing.JLabel();
        fbIngo = new javax.swing.JLabel();
        wppIngo = new javax.swing.JLabel();
        fbLuci = new javax.swing.JLabel();
        wppLuci = new javax.swing.JLabel();
        btSair = new javax.swing.JLabel();
        btReturn = new javax.swing.JLabel();
        Move = new javax.swing.JLabel();
        QuemSomos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IGNORAR.setBackground(new java.awt.Color(153, 153, 153));
        IGNORAR.setEnabled(false);
        getContentPane().add(IGNORAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 30, 20));

        fbAndre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FaceIn.png"))); // NOI18N
        fbAndre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbAndreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fbAndreMouseExited(evt);
            }
        });
        getContentPane().add(fbAndre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        wppAndre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WppIn.png"))); // NOI18N
        wppAndre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wppAndreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wppAndreMouseExited(evt);
            }
        });
        getContentPane().add(wppAndre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        fbIngo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FaceIn.png"))); // NOI18N
        fbIngo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbIngoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fbIngoMouseExited(evt);
            }
        });
        getContentPane().add(fbIngo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        wppIngo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WppIn.png"))); // NOI18N
        wppIngo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wppIngoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wppIngoMouseExited(evt);
            }
        });
        getContentPane().add(wppIngo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        fbLuci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FaceIn.png"))); // NOI18N
        fbLuci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fbLuciMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fbLuciMouseExited(evt);
            }
        });
        getContentPane().add(fbLuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, -1));

        wppLuci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/WppIn.png"))); // NOI18N
        wppLuci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wppLuciMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wppLuciMouseExited(evt);
            }
        });
        getContentPane().add(wppLuci, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, -1, -1));

        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 60, 30));

        btReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/btReturnQSIn.png"))); // NOI18N
        btReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btReturnMouseExited(evt);
            }
        });
        getContentPane().add(btReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 660, -1, -1));

        Move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoveMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MoveMouseMoved(evt);
            }
        });
        getContentPane().add(Move, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 30));

        QuemSomos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/QuemSomos.png"))); // NOI18N
        getContentPane().add(QuemSomos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fbAndreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbAndreMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/FaceOut.png/"));
        fbAndre.setIcon(ico);
    }//GEN-LAST:event_fbAndreMouseEntered

    private void wppAndreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wppAndreMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/WppIn.png/"));
        wppAndre.setIcon(ico);
    }//GEN-LAST:event_wppAndreMouseExited

    private void fbIngoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbIngoMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/FaceOut.png/"));
        fbIngo.setIcon(ico);
    }//GEN-LAST:event_fbIngoMouseEntered

    private void wppIngoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wppIngoMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/WppIn.png/"));
        wppIngo.setIcon(ico);
    }//GEN-LAST:event_wppIngoMouseExited

    private void fbLuciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbLuciMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/FaceOut.png/"));
        fbLuci.setIcon(ico);
    }//GEN-LAST:event_fbLuciMouseEntered

    private void wppLuciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wppLuciMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/WppIn.png/"));
        wppLuci.setIcon(ico);
    }//GEN-LAST:event_wppLuciMouseExited

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked

        Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null,
                "Você deseja sair do jogo?", "ATENÇÃO",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[0]);
        if (i == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btSairMouseClicked

    private void MoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);

    }//GEN-LAST:event_MoveMouseDragged

    private void MoveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveMouseMoved

        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_MoveMouseMoved

    private void btReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseClicked
     Object[] options = {"Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null,
                "Você deseja ao menu principal?", "ATENÇÃO",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                options, options[0]);
        if (i == JOptionPane.YES_OPTION) {
            Menu menu = new Menu();
            menu.setVisible(true);

            this.dispose();
        }

    }//GEN-LAST:event_btReturnMouseClicked

    private void btReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseEntered
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btReturnQSOut.png/"));
        btReturn.setIcon(ico);
    }//GEN-LAST:event_btReturnMouseEntered

    private void btReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btReturnMouseExited
        ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/btReturnQSIn.png/"));
        btReturn.setIcon(ico);
    }//GEN-LAST:event_btReturnMouseExited

    private void fbAndreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbAndreMouseExited
 ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/FaceIn.png/"));
        fbAndre.setIcon(ico);

    }//GEN-LAST:event_fbAndreMouseExited

    private void wppAndreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wppAndreMouseEntered
 ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/WppOut.png/"));
        wppAndre.setIcon(ico);
    }//GEN-LAST:event_wppAndreMouseEntered

    private void fbIngoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbIngoMouseExited
ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/FaceIn.png/"));
        fbIngo.setIcon(ico);

    }//GEN-LAST:event_fbIngoMouseExited

    private void wppIngoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wppIngoMouseEntered
 ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/WppOut.png/"));
        wppIngo.setIcon(ico);


    }//GEN-LAST:event_wppIngoMouseEntered

    private void fbLuciMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fbLuciMouseExited

ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/FaceIn.png/"));
        fbLuci.setIcon(ico);

    }//GEN-LAST:event_fbLuciMouseExited

    private void wppLuciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wppLuciMouseEntered

 ImageIcon ico = new ImageIcon(getClass().getResource("/Imagens/WppOut.png/"));
        wppLuci.setIcon(ico);

    }//GEN-LAST:event_wppLuciMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuemSomos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuemSomos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IGNORAR;
    private javax.swing.JLabel Move;
    private javax.swing.JLabel QuemSomos;
    private javax.swing.JLabel btReturn;
    private javax.swing.JLabel btSair;
    private javax.swing.JLabel fbAndre;
    private javax.swing.JLabel fbIngo;
    private javax.swing.JLabel fbLuci;
    private javax.swing.JLabel wppAndre;
    private javax.swing.JLabel wppIngo;
    private javax.swing.JLabel wppLuci;
    // End of variables declaration//GEN-END:variables
}
